### ISSUE TITLE
Unable to get user information

### ISSUE THREAD

**Issue by SerneLunatic** [Boemska/worktop#7]
Hello,

First - great utility.  The only issue I have is that I cannot get the utility to show any user information whatsoever.  I have tried both host and token auth and no matter what method I use, no user information is shown in worktop.  When I use token auth and add the information into the WorkspaceServer_usermods.sh file, there is a file created in the metaindex location with the user information and PID inside.  But instead of showing me the user information in worktop I receive the following error:

./worktop: line 407: declare: `lookuphash__hostname.fqdn_46756=userid\n': not a valid identifier

I see the issue is with the declare statement:

declare lookuphash__${nodename/-/}_${thisPid}="${thisuser}"

Unfortunately, I do not know how to use declare with periods in the name and since the host uses the FQDN, there are periods.  I tried changing the locale from UTF8 to ISO8859 but that didn't work either.  I might be able to edit the way that WORK folders are created and remove the FQDN from that, but this shouldn't be something I should have to do for this - based on the fact that you have both options of hostname -s and hostname -f (short and full hostnames).  And to be honest, I'm not 100% sure of where that setting is though I will find it.

Do you have any ideas for how to resolve this issue?

**Comment by cj13579** [comment]
Hey @SerneLunatic, I can replicate this and I've made a fix. I'm going to fork the repo and create a pull request.

**Comment by SerneLunatic** [comment]
Thanks for the fix.  I had actually written in a fix as well, but it was janky and not at all elegant.  What I had done was to cut the FQDN information out of the variables for thisHost and whatnot, then ensured I used hostname -s in the _usermods.sh files.  Your solution is better...

And thanks again for this utility.  It is helpful in more ways than one.
